// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
export const messages = {
  "Dashboard": "Dashboard",
  "Reports": "Reports",
  "Admin": "Admin",
  "User Management": "User Management",
  "Add User": "Add User",
  "Edit User": "Edit User",
  "Are you sure you want to delete this user?": "Are you sure you want to delete this user?",
  "Search...": "Search...",
  "All": "All",
  "Active": "Active",
  "Inactive": "Inactive",
  "Previous": "Previous",
  "Next": "Next",
  "Confirm Action": "Confirm Action",
  "This action cannot be undone.": "This action cannot be undone.",
  "All rights reserved.": "All rights reserved.",
  "Privacy Policy": "Privacy Policy",
  "Terms of Service": "Terms of Service"
};
