// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  'validation.email.required': "L'email est obligatoire",
  'validation.email.invalid': 'Veuillez entrer une adresse email valide',
  'validation.password.required': 'Le mot de passe est obligatoire',
  'validation.password.minLength':
    'Le mot de passe doit contenir au moins 8 caracteres',
  'validation.password.lowercase':
    'Le mot de passe doit contenir une lettre minuscule',
  'validation.password.uppercase':
    'Le mot de passe doit contenir une lettre majuscule',
  'validation.password.number': 'Le mot de passe doit contenir un chiffre',
  'validation.password.mismatch': 'Les mots de passe ne correspondent pas',
  'validation.name.required': 'Le nom est obligatoire',
  'validation.name.minLength': 'Le nom doit contenir au moins 2 caracteres',
};
