// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  'Sign In': 'Se Connecter',
  'Sign Out': 'Se Deconnecter',
  'Sign Up': "S'inscrire",
  Email: 'Email',
  Password: 'Mot de passe',
  'Confirm Password': 'Confirmer le mot de passe',
  'Forgot Password?': 'Mot de passe oublie?',
  'Reset Password': 'Reinitialiser le mot de passe',
  "Don't have an account?": "Vous n'avez pas de compte?",
  'Already have an account?': 'Vous avez deja un compte?',
  'This field is required': 'Ce champ est obligatoire',
  'Please enter a valid email address':
    'Veuillez entrer une adresse email valide',
  'Passwords do not match': 'Les mots de passe ne correspondent pas',
  'Invalid email or password': 'Email ou mot de passe invalide',
  'Something went wrong. Please try again.':
    "Une erreur s'est produite. Veuillez reessayer.",
  'Network error. Please check your connection.':
    'Erreur reseau. Veuillez verifier votre connexion.',
  'You are not authorized to perform this action.':
    "Vous n'etes pas autorise a effectuer cette action.",
  'The requested resource was not found.':
    "La ressource demandee n'a pas ete trouvee.",
  'Server error. Please try again later.':
    'Erreur serveur. Veuillez reessayer plus tard.',
  Save: 'Enregistrer',
  Cancel: 'Annuler',
  Delete: 'Supprimer',
  Edit: 'Modifier',
  Submit: 'Soumettre',
  'Loading...': 'Chargement...',
  Retry: 'Reessayer',
  Language: 'Langue',
  Settings: 'Parametres',
  Profile: 'Profil',
  Home: 'Accueil',
  Users: 'Utilisateurs',
};
