// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  'validation.email.required': 'Email is required',
  'validation.email.invalid': 'Please enter a valid email address',
  'validation.password.required': 'Password is required',
  'validation.password.minLength': 'Password must be at least 8 characters',
  'validation.password.lowercase': 'Password must contain a lowercase letter',
  'validation.password.uppercase': 'Password must contain an uppercase letter',
  'validation.password.number': 'Password must contain a number',
  'validation.password.mismatch': 'Passwords do not match',
  'validation.name.required': 'Name is required',
  'validation.name.minLength': 'Name must be at least 2 characters',
};
