// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  'validation.email.required': 'Email is required',
  'validation.email.invalid': 'Please enter a valid email address',
  'validation.password.required': 'Password is required',
  'validation.password.minLength': 'Password must be at least 8 characters',
  'validation.password.lowercase': 'Password must contain a lowercase letter',
  'validation.password.uppercase': 'Password must contain an uppercase letter',
  'validation.password.number': 'Password must contain a number',
  'validation.password.mismatch': 'Passwords do not match',
  'validation.name.required': 'Name is required',
  'validation.name.minLength': 'Name must be at least 2 characters',
  'error.unexpected.title': 'Something went wrong',
  'error.unexpected.message': 'An unexpected error occurred. Please try again.',
  'error.notFound.title': 'Page not found',
  'error.notFound.message': "The page you're looking for doesn't exist.",
  'error.network.title': 'Connection error',
  'error.network.message':
    'Please check your internet connection and try again.',
  'error.unauthorized.title': 'Access denied',
  'error.unauthorized.message': "You don't have permission to view this page.",
  'error.action.tryAgain': 'Try Again',
  'error.action.goHome': 'Go to Home',
  'error.action.goBack': 'Go Back',
  'error.details.title': 'Error Details',
};
