// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  Dashboard: 'Tableau de Bord',
  Reports: 'Rapports',
  Admin: 'Administration',
  'User Management': 'Gestion des Utilisateurs',
  'Add User': 'Ajouter un Utilisateur',
  'Edit User': "Modifier l'Utilisateur",
  'Are you sure you want to delete this user?':
    'Etes-vous sur de vouloir supprimer cet utilisateur?',
  'Search...': 'Rechercher...',
  All: 'Tous',
  Active: 'Actif',
  Inactive: 'Inactif',
  Previous: 'Precedent',
  Next: 'Suivant',
  'Confirm Action': "Confirmer l'Action",
  'This action cannot be undone.': 'Cette action est irreversible.',
  'All rights reserved.': 'Tous droits reserves.',
  'Privacy Policy': 'Politique de Confidentialite',
  'Terms of Service': "Conditions d'Utilisation",
};
