// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = {
  "Dashboard": "Panel",
  "Reports": "Informes",
  "Admin": "Administracion",
  "User Management": "Gestion de Usuarios",
  "Add User": "Agregar Usuario",
  "Edit User": "Editar Usuario",
  "Are you sure you want to delete this user?": "Esta seguro de que desea eliminar este usuario?",
  "Search...": "Buscar...",
  "All": "Todos",
  "Active": "Activo",
  "Inactive": "Inactivo",
  "Previous": "Anterior",
  "Next": "Siguiente",
  "Confirm Action": "Confirmar Accion",
  "This action cannot be undone.": "Esta accion no se puede deshacer.",
  "All rights reserved.": "Todos los derechos reservados.",
  "Privacy Policy": "Politica de Privacidad",
  "Terms of Service": "Terminos de Servicio"
};
