#!/usr/bin/env npx tsx
/**
 * Custom i18n compiler that preserves string keys instead of hashing them.
 *
 * Reads .po files and outputs .ts files with string-keyed message catalogs.
 * This allows using i18n._("Home") at runtime.
 *
 * Usage:
 *   npx tsx scripts/compile-i18n.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

// Configuration - paths to .po files
const CATALOGS = [
  {
    name: 'common',
    basePath: 'packages/i18n/src/locales',
    outputPath: 'packages/i18n/src/locales',
  },
  {
    name: 'web',
    basePath: 'apps/web/app/locales',
    outputPath: 'apps/web/app/locales',
  },
  {
    name: 'expo',
    basePath: 'apps/expo/locales',
    outputPath: 'apps/expo/locales',
  },
];

const LOCALES = ['en', 'es', 'fr'];

interface POEntry {
  msgid: string;
  msgstr: string;
}

/**
 * Parse a .po file and extract msgid/msgstr pairs
 */
function parsePOFile(filePath: string): Map<string, string> {
  if (!fs.existsSync(filePath)) {
    console.warn(`  Warning: File not found: ${filePath}`);
    return new Map();
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const messages = new Map<string, string>();

  let currentMsgId: string | null = null;
  let currentMsgStr: string | null = null;
  let inMsgId = false;
  let inMsgStr = false;

  for (const line of lines) {
    // Start of msgid
    if (line.startsWith('msgid ')) {
      // Save previous entry
      if (currentMsgId && currentMsgId !== '') {
        messages.set(currentMsgId, currentMsgStr || currentMsgId);
      }
      currentMsgId = extractQuotedString(line.slice(6));
      currentMsgStr = null;
      inMsgId = true;
      inMsgStr = false;
      continue;
    }

    // Start of msgstr
    if (line.startsWith('msgstr ')) {
      currentMsgStr = extractQuotedString(line.slice(7));
      inMsgId = false;
      inMsgStr = true;
      continue;
    }

    // Continuation of multi-line string
    if (line.startsWith('"')) {
      const continued = extractQuotedString(line);
      if (inMsgStr && currentMsgStr !== null) {
        currentMsgStr += continued;
      } else if (inMsgId && currentMsgId !== null) {
        currentMsgId += continued;
      }
    }
  }

  // Don't forget last entry
  if (currentMsgId && currentMsgId !== '') {
    messages.set(currentMsgId, currentMsgStr || currentMsgId);
  }

  return messages;
}

/**
 * Extract string from PO quoted format
 */
function extractQuotedString(s: string): string {
  const match = s.trim().match(/^"(.*)"$/);
  if (!match) return s;
  return match[1]
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}

/**
 * Generate TypeScript/JavaScript output
 */
function generateOutput(
  messages: Map<string, string>,
  format: 'esm' | 'cjs'
): string {
  const entries: string[] = [];

  for (const [key, value] of messages) {
    // Escape for JSON
    const escapedKey = JSON.stringify(key);
    const escapedValue = JSON.stringify(value);
    entries.push(`  ${escapedKey}: ${escapedValue}`);
  }

  const messagesObj = `{\n${entries.join(',\n')}\n}`;

  if (format === 'esm') {
    return `// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
export const messages = ${messagesObj};
`;
  } else {
    return `// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
/* eslint-disable */
module.exports.messages = ${messagesObj};
`;
  }
}

/**
 * Generate TypeScript declaration file
 */
function generateDts(): string {
  return `// Auto-generated by scripts/compile-i18n.ts - DO NOT EDIT
export declare const messages: Record<string, string>;
`;
}

/**
 * Main function
 */
async function main() {
  console.log('📦 Compiling i18n catalogs with string keys\n');

  for (const catalog of CATALOGS) {
    console.log(`\n📁 Processing ${catalog.name}...`);

    for (const locale of LOCALES) {
      const poPath = path.resolve(
        ROOT_DIR,
        catalog.basePath,
        locale,
        'messages.po'
      );

      console.log(`  ${locale}: ${path.relative(ROOT_DIR, poPath)}`);

      const messages = parsePOFile(poPath);

      if (messages.size === 0) {
        console.log(`    ⚠ No messages found`);
        continue;
      }

      console.log(`    ✓ ${messages.size} messages`);

      // Output directory
      const outputDir = path.resolve(ROOT_DIR, catalog.outputPath, locale);
      fs.mkdirSync(outputDir, { recursive: true });

      // Generate ESM output (.mjs)
      const esmOutput = generateOutput(messages, 'esm');
      const esmPath = path.join(outputDir, 'messages.mjs');
      fs.writeFileSync(esmPath, esmOutput);

      // Generate CJS output (.js) for Expo/React Native
      const cjsOutput = generateOutput(messages, 'cjs');
      const cjsPath = path.join(outputDir, 'messages.js');
      fs.writeFileSync(cjsPath, cjsOutput);

      // Generate TypeScript declarations
      const dtsOutput = generateDts();
      fs.writeFileSync(path.join(outputDir, 'messages.d.mts'), dtsOutput);
      fs.writeFileSync(path.join(outputDir, 'messages.d.ts'), dtsOutput);
    }
  }

  console.log('\n✅ Done! Compiled all catalogs with string keys.');
}

main().catch(console.error);
